### ISSUE TITLE
Meteor Tracker Data integration

### ISSUE THREAD

**Issue by Akryum** [Akryum/meteor-vue-component#10]
https://github.com/Akryum/meteor-vue-component/tree/master/packages/vue#usage

**Comment by green-coder** [comment]
Hello, you might want to follow this Enhancement Request : https://github.com/vuejs/vue/issues/5258

I am currently trying to make the connection between tracker and Vue's reactivity easier. My work is heavily based on your plugin, I hope to be able to contribute at some point.

**Comment by green-coder** [comment]
Please ignore my previous message, apparently @mitar did an amazing work on the integration already.
