### ISSUE TITLE
Problem when doing a deploy using mupx

### ISSUE THREAD

**Issue by alexandesigner** [Akryum/meteor-vue-component#104]
I'm having a problem while doing a deploy using mupx, but anyone?

Well, I just cloned the repository with the basic example, I followed these instructions:

Https://github.com/Akryum/meteor-vue-example#steps-to-reproduce and then I set up mupx normally, I was able to do the `` setup`` but in `` deploy`` it is giving a problem that I believe Be referring to `` vue-component-dev-server``, someone can check the problem if it is persistent or maybe it's something with me.

Error: ``Cannot read property 'length' of null``

![captura de tela 2017-01-15 as 19 25 13](https://cloud.githubusercontent.com/assets/3044907/21966745/01e09f3a-db58-11e6-8288-56ff7ee53681.png)

**Comment by Akryum** [comment]
This package shouldn't be included in production mode. Did you set the
NODE_ENV var to 'production'?

Le dim. 15 janv. 2017 à 23:23, Allan Alexandre <notifications@github.com> a
écrit :

**Comment by alexandesigner** [comment]
Yes, I tested adding directly to the configuration file ``mup.json``
```
"env": {
  "NODE_ENV": "production"
}
```
.. but still the problem persisted, have you ever used ``mupx`` ? What do you usually use for actually ``deploy`` in meteor applications?

**Comment by Akryum** [comment]
I've used a docker platform.

**Comment by nizulzaim** [comment]
Why dont you run mup logs --tail=50 first.

**Comment by alexandesigner** [comment]
> I've used a docker platform.

Standalone? Why mupx uses Docker internally .. where exactly can I activate production mode?

When I squeeze locally with a ``meteor --production`` flag, everything works normally. In a way I'm going to keep breaking my head to solve.

Thanks for the attention Akryum

> Why dont you run mup logs --tail=50 first.

If I am appealing to the community, it is because my attempts to resolve alone are exhausted.

**Comment by Akryum** [comment]
Maybe he meant that you could post your full logs here.

I've built meteor apps then used them in a docker farm with vanilla docker and docker-compose (no additional tool).

**Comment by nizulzaim** [comment]
No please post here the log tail. I want to see it

**Comment by alexandesigner** [comment]
Of course, is not very different from the previous image.

``$mupx logs --tail==50``

![captura de tela 2017-01-17 as 20 25 08](https://cloud.githubusercontent.com/assets/3044907/22044639/6acec7b8-dcf4-11e6-9be0-92b77da4da3c.png)

**Comment by nizulzaim** [comment]
I thought u are using mup application! So sorry. Yeah if you said about
mupx, i already tried it before and yes you cant use it because you cant
setup custom docker here. I recommend you to use mup because it can setup
custom docker image.

**Comment by alexandesigner** [comment]
I'll try to use the mup.. if I succeed or not, post the result here.. anyway, I'll study vanilla docker more.. I think it's an approach that will give me more control.

**Comment by alexandesigner** [comment]
The problem was really the way NODE_ENV=production mode was not being adjusted .. 

However, I changed the ``mupx`` by [``meteor-now``](https://www.npmjs.com/package/meteor-now) and it was successful!
