### ISSUE TITLE
Extract css to external .css file

### ISSUE THREAD

**Issue by eybarta** [Akryum/meteor-vue-component#109]
Hi, thanks for you work!

Is there an option to extract the css build to an external file and call it from the html?

Something similar to webpack's ExtractTextPlugin?

or if not, is there a way to compile the css to the html not at run-time..?

My issue is when loading the page, there's about a second delay until styles from components
are rendered into HEAD.. So my question is, what's the best way to solve this?

if not with 1 of the options above, is there a way to tell when the components css is ready?
(tried mounted(), but it happens way before..)

thx

**Comment by Akryum** [comment]
This is only true in development mode, to enable Hot replacement of the `<style>` of `.vue` files. When in production mode, all the CSS is outputted in a minified file by Meteor as usual.

**Comment by eybarta** [comment]
Thats good to know.. thank you.

**Comment by AsafAgranat** [comment]
Thanks for the ref.
And thanks for your efforts on this project. Much appreciated!
