### ISSUE TITLE
db.find({params}) undefined causing TypeError

### ISSUE THREAD

**Issue by janat08** [Akryum/meteor-vue-component#115]
Uncaught TypeError: Cannot read property 'skillList' of undefined

    <tables :charSkills="skills.skillList">
    </tables>

  meteor: {
    **skills**() {
      var param = this.$route.params.name.replace('_', ' ')
      return CharsInfo.findOne({name: param})
    }
  },

**Comment by janat08** [comment]
https://gist.github.com/janat08/7536d755912148820c02553a24ab5dd7
Is likely not a bug, AFAIK findone is a fetch operation, putting findOne within component returns undefined either way.

**Comment by janat08** [comment]
The data actually comes through, but it causes errors that stop app from running.

**Comment by Akryum** [comment]
Try something like this:

```
data () {
  return {
    // ...
    skills: {},
  },
},

meteor: {
  skills: {
    params () {
      return this.$route.params.name.replace('_', ' ')
    },
    update (param) {
      return CharsInfo.findOne({name: param})
    },
  },
},
```

**Comment by Akryum** [comment]
Also, guard the template parts that uses `skills`, which might be undefined until loaded:

```html
<tables v-if="skills" :charSkills="skills.skillList">
</tables>
```

**Comment by janat08** [comment]
So it won't work without the v-if="skills".

**Comment by janat08** [comment]
Is passing meteor data as prop is what makes it break, otherwise it being fine if it were all happening on the same template?

**Comment by janat08** [comment]
It also for example causes something like Meteor.user().id not working in find params.

**Comment by janat08** [comment]
There're also issues with Meteor.user() not loading, if you reload page or land on that page.
