### ISSUE TITLE
unstyled HTML flashing on first load

### ISSUE THREAD

**Issue by AsafAgranat** [Akryum/meteor-vue-component#119]
On first load/page-refresh, the unstyled HTML is flashing for a fraction of a second before rendering properly. v-cloak doesn't solve the issue because the templates/components content gets mounted properly.
What does seem to happen is that, once a component gets mounted, the styles get injected into the `<head>` with a delay. This causes an initial flickering on unstyled HTML before the CSS applies.

**Comment by Akryum** [comment]
This is only true in development mode for Hot Module Replacement. See [#109](https://github.com/Akryum/meteor-vue-component/issues/109#issuecomment-277065298)
