### ISSUE TITLE
Vuex integration

### ISSUE THREAD

**Issue by Akryum** [Akryum/meteor-vue-component#2]
*Discussion for vuex integration with the meteor data stack and apollo*

**Comment by niallobrien** [comment]
Vuex support would be awesome.

**Comment by smolinari** [comment]
:+1: 

This would be the more interesting development for connecting Vue to a GraphQL server. It will be interesting to see how to work with or around the Redux store the Apollo team decided to include. 

Scott

**Comment by smolinari** [comment]
I watched @yyx990803 - Evan You discuss Vue 2.0 yesterday, and he mentioned that Vue 2.0 should work better with a Redux store, soooo maybe this isn't necessary? 

Scott

**Comment by Akryum** [comment]
I didn't have the time to watch it yet.

**Comment by smolinari** [comment]
Yeah, it was just a quick comment from Evan to a question asked towards the end. 

Scott

**Comment by Akryum** [comment]
Implemented in [akryum:vuex](https://github.com/Akryum/meteor-vue-component/tree/master/packages/vuex#installation).

**Comment by smolinari** [comment]
Cool stuff! 

Have you looked at Vue 2.0? It will most likely mean some rework, but from what I understand, it will be well worth it. 

Scott

**Comment by Akryum** [comment]
I follow the vue 2.0 development, but I will start moving to it when it becomes stable (there are still breaking changes happening).

**Comment by smolinari** [comment]
Yes. Sounds good! Great work btw. 

Scott
