### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by Akryum** [Akryum/meteor-vue-component#23]
Using vue-router.
Maybe with some sort of fastrender functionnality?

**Comment by Akryum** [comment]
For fastrender, we may use this: http://router.vuejs.org/en/pipeline/data.html

**Comment by Akryum** [comment]
This seems to work already:
```javascript
FastRender.route('/forum', function(params) {
  this.subscribe('threads');
});
```

**Comment by janat08** [comment]
What about additionally enabling: meteorhacks:subs-manager. Storing all of the data from subscription after user leaves the page in case he comes back.

**Comment by Akryum** [comment]
You can use meteorhacks:subs-manager instead if you want.

```javascript
Vue.config.meteor.subscribe = function(...args) {
  /* Do whatever you like */
  return /* Any subscription-like object */
};
```

**Comment by janat08** [comment]
Yet, I imagine there should be a trigger for like on created that would refresh the cache?
