### ISSUE TITLE
Global default lang configuration

### ISSUE THREAD

**Issue by Akryum** [Akryum/meteor-vue-component#27]
Configure default language used in `<template>`, `<script>` and `<style>` in your components with a `.vuerc` file at your project root.

**Comment by laurentpayot** [comment]
Is it really a good thing? It would create a dependency on `.vuerc` file whereas the purpose of "**single file** components" are to be self-sufficient...
And how would my IDE (atom) detect the languages?

**Comment by Akryum** [comment]
Good points!
