### ISSUE TITLE
Uncaught TypeError: Cannot read property 'createRecord' of undefined

### ISSUE THREAD

**Issue by nizulzaim** [Akryum/meteor-vue-component#28]
Hi, I dont know what is this problem. Im trying to play with your package that are look promising. With only 3 files that are created, this problem are already show up.

Here is my client/main.html

```
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Meteor Vue App</title>
</head>
<body>
    <app></app>
</body>
```

Here is client/main.js

```
import { Vue } from 'meteor/akryum:vue';
import { Meteor } from 'meteor/meteor';
import App from '/imports/ui/App.vue';

Vue.component('app', App);
```

And here is imports/ui/App.vue

```
<template>
    <div class="app">
        Try this
    </div>
</template>

<script>
    export default {
        ready() {
            console.log("hello world");
        }
    }
</script>
```

I am using version METEOR@1.3.2.4 in Windows.

**Comment by Akryum** [comment]
I think I know what's going on. I'm writing a potential fix.

**Comment by nizulzaim** [comment]
Thank you for quick reply.. Love to test for you.

**Comment by Akryum** [comment]
Let me know if it still crashes with akrym:vue-component@0.3.2

**Comment by nizulzaim** [comment]
No error anymore. Thank you!
