### ISSUE TITLE
Vue Router API limit to start and map

### ISSUE THREAD

**Issue by nizulzaim** [Akryum/meteor-vue-component#36]
Hi, do you only implement Router.map and Router.start? I don't see any debug result for Router.go, Router.stop and other.

**Comment by Akryum** [comment]
You can access all the vue-router methods with `Router.lib`. I need to document that in the readme.
In your vue instances, you can still use the standard `this.$router`and `this.$route`.

**Comment by nizulzaim** [comment]
Alright. Thanks.. work now.. Did not see it in Router.lib before.

**Comment by Akryum** [comment]
I added `Router.on` since it makes sense to have it for route definitions.

**Comment by nizulzaim** [comment]
I see. I just develop some UI package for Material Design using your packages. It work very well. I will test it more to give feedback about your packages.
