### ISSUE TITLE
jQuery errors

### ISSUE THREAD

**Issue by janat08** [Akryum/meteor-vue-component#42]
Putting jquery after ready: function () {etc} with a syntax error of additional }, or something wrecks havoc without an error message in CMD or terminal (that makes sense) when also using Blaze. Is this an upstream issue?

**Comment by Akryum** [comment]
How does your code look like?

**Comment by janat08** [comment]
`
=> Client modified -- refreshing (x11){ [SyntaxError: Unexpected token (17:6)] pos: 317, loc: { line: 17, column: 6 } }
{ [SyntaxError: Unexpected token (17:6)] pos: 317, loc: { line: 17, column: 6 } }

=> Errors prevented startup:

   While processing files with akryum:vue-component (for target
   web.browser):

   C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\location.js:22:13:
   Unexpected token (17:6)
   at Parser.pp.raise
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\location.js:22:13)
   at Parser.pp.unexpected
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\util.js:89:8)
   at Parser.pp.parseBindingAtom
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\lval.js:177:12)
   at Parser.pp.parseMaybeDefault
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\lval.js:223:23)
   at Parser.pp.parseBindingList
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\lval.js:203:23)
   at Parser.pp.parseMethod
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\expression.js:880:22)
   at Parser.pp.parseObjPropValue
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\expression.js:799:10)
   at Parser.parseObjPropValue
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\plugins\flow.js:298:13)
   at Parser.pp.parseObj
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\expression.js:777:10)
   at Parser.pp.parseExprAtom
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\expression.js:486:19)
   at Parser.parseExprAtom
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\plugins\jsx\index.js:18:22)
   at Parser.pp.parseExprSubscripts
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\expression.js:272:19)
   at Parser.pp.parseMaybeUnary
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\expression.js:252:19)
   at Parser.pp.parseExprOps
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\expression.js:183:19)
   at Parser.pp.parseMaybeConditional
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\expression.js:165:19)
   at Parser.pp.parseMaybeAssign
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\expression.js:128:19)
   at Parser.pp.parseExpression
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\expression.js:92:19)
   at Parser.pp.parseReturnStatement
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\statement.js:333:26)
   at Parser.pp.parseStatement
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\statement.js:107:19)
   at Parser.parseStatement
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\plugins\flow.js:30:22)
   at Parser.pp.parseBlockBody
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\statement.js:529:21)
   at Parser.pp.parseTopLevel
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\statement.js:36:8)
   at Parser.parse
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\index.js:129:19)
   at Object.parse
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\index.js:47:47)
   at parse
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:38:29)
   at
   C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:58:15
   at Cache.Cp.get
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\cache.js:94:19)
   at Object.compile
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:47:23)
   at Object.Babel.compile (packages/babel-compiler/babel.js:26:1)
   at VueComponentTagHandler.getResults
   (packages/vue-component/plugin/tag-handler.js:107:28)
   at VueComponentCompiler.compileTags
   (packages/vue-component/plugin/vue-compiler.js:267:20)
   at VueComponentCompiler.compileOneFileWithContents
   (packages/vue-component/plugin/vue-compiler.js:42:19)
   at VueComponentCompiler.compileOneFile
   (packages/vue-component/plugin/vue-compiler.js:27:17)
   at packages/caching-compiler/caching-compiler.js:292:32
   at
   C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:324:29
   at
   C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:44:16
   at packages/caching-compiler/caching-compiler.js:309:9
   at
   C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-component\0.4.0\plugin.vue-component.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:221:35)
   at VueComponentCompiler.processFilesForTarget
   (packages/caching-compiler/caching-compiler.js:277:11)


=> Your application has errors. Waiting for file change.
 `

**Comment by janat08** [comment]
On second thought the error is that line 16-17 as the first statement in error report relative to the actual beginning of the script start tag, other wise your first impression is going to be that its off by the length of <template> tags.

**Comment by Akryum** [comment]
There is room for improvement regarding the source maps, but it should work well in the browser debugger when you click on the error line number.

**Comment by janat08** [comment]
Maybe atleast log that the count of lines starts from script tag, and meteor won't necessarily boot you into error window possibly even you refresh the page (Im uncertain if you may actually click on a line number).

**Comment by Akryum** [comment]
What is the code inside your `render() { ... }`?

**Comment by janat08** [comment]
I used
  ready: function() {
    $('.right.menu.open').on("click",function(e){
      e.preventDefault();
      $('.ui.vertical.menu').toggle();
    });
    $('.ui.dropdown').dropdown();
  }

**Comment by Akryum** [comment]
And the complete vue file content?

**Comment by janat08** [comment]
It's no longer an accurate reproduction, but at that point I belief I would've also had handlebars that are commented out and semantic ui:

```
<template>
  <div class="navBar">
    <div class="ui grid">
<!--  <div class="computer tablet only row"> -->
  <div class="ui inverted fixed menu navbar page grid">
<!--    <a href="" class="brand item">Garlic</a> -->
    <a href="/" class="item">Garlic</a>
    <a href="/auction" class="item">Auction</a>
    <a href="/corporate/list" class="item">Corporate</a>
<!--    <a>{{> loginButtons}}</a>
    {{#if currentUser}}
    <a href="/profile">User profile</a>
    {{/if}} -->
</div>

<div class="ui grid">
  <div class="computer tablet only row">
    <div class="ui inverted fixed menu navbar page grid">
      <a href="" class="brand item">Project Name</a>
      <a href="" class="active item">Home</a>
      <a href="" class="item">About</a>
      <a href="" class="item">Contact</a>
      <div class="right menu">
        <a href="" class="item">Fixed top</a>
      </div>
    </div>
  </div>
  <div class="mobile only row">
      <div class="ui fixed inverted navbar menu">
          <a href="" class="brand item">Project Name</a>
          <div class="right menu open">
              <a href="" class="menu item">
                  <i class="content icon"></i>
              </a>
          </div>
      </div>
      <div class="ui vertical navbar menu">
        <a href="" class="active item">Home</a>
        <a href="" class="item">About</a>
        <a href="" class="item">Contact</a>
        <div class="menu">
          <a href="" class="active item">Default</a>
          <a href="" class="item">Static top</a>
          <a href="" class="item">Fixed top</a>
        </div>
      </div>
    </div>
</div>
</template>

<script>
import {jQuery} from 'meteor/jquery';

export default {
  ready: function() {
    $('.right.menu.open').on("click",function(e){
      e.preventDefault();
      $('.ui.vertical.menu').toggle();
    });
    $('.ui.dropdown').dropdown();
  }
}
</script>

<style scoped>
.widget {
  background: #a0ddc4;
  padding: 12px;
  border-radius: 3px;
  width: 300px;
  border-bottom: solid 1px #40b883;
}
````

**Comment by Akryum** [comment]
Try using `import {$} from 'meteor/jquery';` instead.

**Comment by Akryum** [comment]
I just made a test and I had no errors while running it. You can check it in the [jquery branch](https://github.com/Akryum/meteor-vue-blaze/tree/jquery) of the example project.

**Comment by janat08** [comment]
The issue is with jquery error reports that give the "wrong" error line as in if you have an extra comma or a bracket somewhere, which is a shame if you have written a file in a go and than have to through all of it if you don't figure that actual line where error is at starts counting from starting <script> tag rather than includes template.

**Comment by Akryum** [comment]
See #46
