### ISSUE TITLE
Vue.js + Blaze (importing blaze into vue.js)

### ISSUE THREAD

**Issue by janat08** [Akryum/meteor-vue-component#44]
So gotta wonder if integrating blaze, for that case where I'd like to use a blaze package on top of vue.js rather than going blaze first preemptively, into vue.js would be easier instead of serving vue.js in through blaze? Maybe have blaze -vue -example mix and match them with routers.

**Comment by Akryum** [comment]
I'll look into this and maybe make a special vue directive to include a blaze template into a vue component (like MDG did for React).

**Comment by janat08** [comment]
I'm still somewhat consistently failing to make vue.js render in my baze.

<template>
  <div class="navBar">

<script>
import {jQuery} from 'meteor/jquery';

export default {
  ready: function() {

import {Vue} from 'meteor/akryum:vue';
import NavBar from '/imports/ui/NavBar.vue';


Template.abba.rendered = function() {
  var vm = new Vue({
    el: '#abba',
    template: '<div><navBar></navBar></div>',
    components: {
      NavBar
    }
  });
}

<template name="mainLayout">
		{{> abba}}
	<div height="160px"><p></p></div>
	<div id="mainContent">
		{{> Template.dynamic template=content}}
	</div>
</template>

<template name="abba">
  <div id="abba"></div>
</template>

**Comment by Akryum** [comment]
Is it related to #42 ?

**Comment by janat08** [comment]
Not so much, that jquery error occured when I literally just copied and pasted on top of Widget.vue

**Comment by janat08** [comment]
In case you belief that Im using render command, I mean that I can a blank screen with none of Vue rendering.

**Comment by janat08** [comment]
whats wrong doc?

**Comment by Akryum** [comment]
If you have a problem rendering a vue component in a blaze template, please create another issue, because right now I'm lost. I though you wanted to use a blaze template in your vue component (your initial post).
