### ISSUE TITLE
Hopelessly won't import Vue.js as blaze template

### ISSUE THREAD

**Issue by janat08** [Akryum/meteor-vue-component#45]
I'm still somewhat consistently failing to make vue.js render in my baze.

NavBar.vue
```
<template>
  <div class="navBar">

<script>
import {jQuery} from 'meteor/jquery';
export default {
  ready: function() {
```
mainLayout.js
```
import {Vue} from 'meteor/akryum:vue';
import NavBar from '/imports/ui/NavBar.vue';

Template.abba.rendered = function() {
  var vm = new Vue({
    el: '#abba',
    template: '<div><navBar></navBar></div>',
    components: {
      NavBar
    }
  });
}
```
mainLayout.html
```
<template name="mainLayout">
        {{> abba}}
    <div height="160px"><p></p></div>
    <div id="mainContent">
        {{> Template.dynamic template=content}}
    </div>
</template>
```
abba.html
```
<template name="abba">
  <div id="abba"></div>
</template>

**Comment by Akryum** [comment]
Do you have any error outputs in the server console or in the browser?

**Comment by janat08** [comment]
I'm switching to the akryum:vue-blaze-template.  Although the actual repo for my project (this is test) wouldn't work after having copied and pasted example Widget, even. There's also a navbar within the layout as .vue. It's entirely possible that Im just disturbed enough that I fail to keep track of chain of hoops.

ame collision as I named both the blaze template and 

FlowRouter.route('/', {
  action: function() {
    BlazeLayout.render("mainLayout", {content: "homePage"});
  }
});

Errors in console:
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
Failed to parse SourceMap: http://localhost:3004/33998e57ab6bf17e32e84d105be0dd62f5f105ea.map
install.js:85

Uncaught Error: Cannot find module 'vue'require @ install.js:85meteorInstall.node_modules.meteor.akryum:vue.install.js @ install.js:1fileEvaluate @ install.js:153require @ install.js:82meteorInstall.node_modules.meteor.akryum:vue.index.js @ index.js:1fileEvaluate @ install.js:153require @ install.js:82(anonymous function) @ akryum_vue.js?hash=6a95c5e…:267(anonymous function) @ akryum_vue.js?hash=6a95c5e…:278 akryum_vue-component-dev-client.js?hash=60e71e4…:13182

Uncaught TypeError: Cannot read property 'Vue' of undefined(anonymous function) @ akryum_vue-component-dev-client.js?hash=60e71e4…:20(anonymous function) @ akryum_vue-component-dev-client.js?hash=60e71e4…:13182 global-imports.js?hash=83fa817…:10 

Uncaught TypeError: Cannot read property 'Vue' of undefined(anonymous function) @ global-imports.js?hash=83fa817…:10 app.js?hash=2f866dc…:1

Uncaught ReferenceError: meteorInstall is not defined(anonymous function) @ app.js?hash=2f866dc…:1 router.js:347 

There is no route for the path: /Router._notfoundRoute @ router.js:347(anonymous function) @ router.js:535(anonymous function) @ index.js:474nextEnter @ index.js:306page.dispatch @ index.js:312page.replace @ index.js:275self._page.(anonymous function) @ router.js:382page.start @ index.js:168page @ index.js:102Router.initialize @ router.js:391(anonymous function) @ _init.js:9maybeReady @ startup_client.js:26loadingCompleted @ startup_client.js:38 extensions::uncaught_exception_handler:8

**Comment by janat08** [comment]
Will upload the repo once I learn how Git Kraken wants me to deal with remotes.

**Comment by Akryum** [comment]
I will certainly help!

**Comment by janat08** [comment]
https://github.com/janat08/garlic2--exmp-

**Comment by janat08** [comment]
Any revelations? One of the meteor files couldn't be published.

**Comment by Akryum** [comment]
Just looking at the source files, in you `abba.js`, try `template: '<div><nav-bar></nav-bar></div>'`

**Comment by Akryum** [comment]
I was able to run your project without any error:

![garlic2](https://cloud.githubusercontent.com/assets/2798204/16732308/cb3e3ace-477c-11e6-986f-c3e8de038911.png)

In your project folder, I did:

```
meteor update
meteor npm install
meteor
```

**Comment by Akryum** [comment]
> Uncaught Error: Cannot find module 'vue'require @ install.js:85meteorInstall.node_modules.meteor.akryum:vue.install.js @ install.js:1fileEvaluate @ install.js:153require @ install.js:82meteorInstall.node_modules.meteor.akryum:vue.index.js @ index.js:1fileEvaluate @ install.js:153require @ install.js:82(anonymous function) @ akryum_vue.js?hash=6a95c5e…:267(anonymous function) @ akryum_vue.js?hash=6a95c5e…:278 akryum_vue-component-dev-client.js?hash=60e71e4…:13182

It seems you forgot to install the npm depencencies with the `meteor npm install` command.

**Comment by janat08** [comment]
OMG, the html is case insensitive. I for some reason also forgot to look at the console. As an after though, it matters not if both the blaze template, vue component, and everything else that would be name the same since all of the things can't collide since all of them are different type of things|?

**Comment by Akryum** [comment]
Blaze template names and vue component names can't collide. ;)

**Comment by AhmedShibob** [comment]
@Akryum 
i have the same issue but i use  https://github.com/RocketChat/Rocket.Chat 
how i can use vue inside it
