### ISSUE TITLE
Script sourcemap line numbers are off

### ISSUE THREAD

**Issue by Akryum** [Akryum/meteor-vue-component#46]
Start at 1 with the begining of the script tag instead of the begining of the file.

**Comment by MartinBucko** [comment]
+1 on this, also there is problem with coffee-script files, it don't show correct line with compilation error. Just show first line where start script..

**Comment by Akryum** [comment]
@benjamn I'm struggling to use the full `.vue` files content as the base for the `sourceMap` option of `addJavaScript`. It's always end up with only the JavaScript part of the file (and thus wrong line numbers compared to the original file).
