### ISSUE TITLE
Improve error logging

### ISSUE THREAD

**Issue by Akryum** [Akryum/meteor-vue-component#48]
- [x] Too verbose
- [x] More clearer details

**Comment by janat08** [comment]
Actual file name with the error would be a good start. I haven't got clue whats what:
"While processing files with akryum:vue-component (for target web.browser):"

**Comment by janat08** [comment]
or component, or like the block of code that the error is in.

**Comment by janat08** [comment]
In mean time if I disable blaze will my errors logs be okay?

**Comment by Akryum** [comment]
I didn't have time to look at this this weekend, I may tackle it next week.

**Comment by janat08** [comment]
Fine, but it's already Monday here thus it looked you were going to look at it like in 7 days.

**Comment by Akryum** [comment]
Well, it's still sunday here! :smile:

**Comment by nizulzaim** [comment]
Without blaze, the error logs will give same output. It is good improvement when you add this feature.

**Comment by Akryum** [comment]
In the 0.6.4 version, the errors look like this:

    [vue-component] Error while compiling in tag <script>: Unexpected token (23:9) -> in imports/bourse-echange/client/ui/RequestForm.vue at line 73 col 9
