### ISSUE TITLE
Vue router and blaze embed

### ISSUE THREAD

**Issue by janat08** [Akryum/meteor-vue-component#49]
So have you tested v-blaze with vue router, as it doesn't appear to work.

This line is apparently has unidentified property:     const template = Template[templateName];

**Comment by janat08** [comment]
Played around with those simple instructions, hopefully there's an actual bug here with no embarrassment for my part :P

**Comment by janat08** [comment]
Well fine, so i've rendered the widget into vue_demo blaze template that I rendered through v-blaze.

**Comment by janat08** [comment]
What is new value suppose to be as a variable?

**Comment by Akryum** [comment]
Inside the directive update method, it's the new value of the expression you pass to the directive ([vue doc](http://vuejs.org/guide/custom-directive.html)).
For the `v-blaze="expression"` it's the template name.

**Comment by janat08** [comment]
Is there a lame way of importing blaze into vue.js that's maybe more so surefire? Are you interested in seeing my repo?

**Comment by Akryum** [comment]
> maybe more so surefire

What do you mean?

> Are you interested in seeing my repo?

Sure!

**Comment by janat08** [comment]
whats ur bitbucket account?

**Comment by Akryum** [comment]
Akryum

**Comment by janat08** [comment]
https://bitbucket.org/janat08/garlic

Shared: theres v-blaze="'corporateApplyButton'" in corporateList.vue that's reached via corporate button in navbar

**Comment by janat08** [comment]
npm bcrypt is outdated since it's latest compatible version, and everything else is up to date.

**Comment by Akryum** [comment]
There is no corporateList.vue in your repo.

**Comment by janat08** [comment]
Sec just realized im yet to commit changes

**Comment by janat08** [comment]
pushed

**Comment by janat08** [comment]
Gave you write access in case theres mistake.
