### ISSUE TITLE
Consolidate all of the examples into a single repository/app

### ISSUE THREAD

**Issue by janat08** [Akryum/meteor-vue-component#50]
Makes it easier to navigate and test. Additionally maybe it's possible to use Flow Router with vue.js?

**Comment by janat08** [comment]
Like label what package is reponsible for what.

**Comment by Akryum** [comment]
[The project repo](https://github.com/Akryum/meteor-vue-component) is a consolidated example of the different packages.

**Comment by janat08** [comment]
I meant the same codebase.

**Comment by Akryum** [comment]
It is the same codebase. [See instructions](https://github.com/Akryum/meteor-vue-component#development-project).
