### ISSUE TITLE
Imported files don't trigger rebuilding and hot-reloading

### ISSUE THREAD

**Issue by Akryum** [Akryum/meteor-vue-component#51]
- [x] Dependency manager watching imported files
- [x] less
- [x] sass
- [x] stylus

**Comment by Neijin** [comment]
Hi @Akryum !
It seems like Stylus imported files from the "style" tag of a Vue component don't trigger rebuilding and hot-reloading anymore.

**button.vue**
`<style lang="stylus" scoped>
    @import "./button.import.styl";
</style>`

**button.import.styl**
`.button
{
   color red
   cursor pointer
}`

Modifications of the button.import.styl file doesn't do anything.
