### ISSUE TITLE
Animations like _uihooks

### ISSUE THREAD

**Issue by inssitu** [Akryum/meteor-vue-component#54]
Any idea about how to animate a list from a subscription like blaze do with insertElement, moveElement and removeElement?

![posts-animation](https://cloud.githubusercontent.com/assets/8522674/17045160/7a1826fc-4fc7-11e6-8e27-505fca304dac.gif)

Thanks

**Comment by inssitu** [comment]
I have tried to use [vue animated list](https://github.com/vuejs/vue-animated-list) without success.

**Comment by Akryum** [comment]
I'll look into this. Maybe we can improve the minimongo cursor handling.

**Comment by inssitu** [comment]
That woulb be awasome @Akryum

**Comment by mitar** [comment]
Have you tried doing `:key="_id"` in your for loop for the list? In that case Vue will use Minimongo's `_id` and move elements around.

**Comment by Akryum** [comment]
As @mitar said, you can now use the `key` special attribute starting with Vue 2.0. It will behave as you wanted thanks to the virtual-dom now powering Vue and new transitions [documented here](https://vuejs.org/v2/guide/transitions.html#List-Transitions).

If you need further help, don't hesitate to ask here.
