### ISSUE TITLE
Devtools

### ISSUE THREAD

**Issue by nicooprat** [Akryum/meteor-vue-component#57]
Any way to use Vue Devtools with this package? https://github.com/vuejs/vue-devtools

I installed it on Chrome but it looks like the extension can't "find" Vue in the app...

Thanks

**Comment by Akryum** [comment]
I was able to use the Devtools using the akryum:vue package. Try to refresh your app and close/open the Chrome devtools.

**Comment by nicooprat** [comment]
Can't make it work unfortunately. It worked with a simple Vue project though (without Meteor). I'm also using `akryum:vue-component`, that might be causing the issue?

**Comment by pandada8** [comment]
I can use devtool in local develop, but failed after `meteor build`,  is this expected ?

**Comment by ackzell** [comment]
It's been a while, and guess that is already known, but DevTools works all right with the following versions:

```
akryum:vue@1.2.2
akryum:vue-component@0.7.11
akryum:vue-component-dev-client@0.2.2
akryum:vue-component-dev-server@0.0.3
akryum:vue-router2@0.0.2
```

**Comment by J4si3k** [comment]
I run vue-devtools on my meteor project on android phone with this [instruction](https://www.npmjs.com/package/@vue/devtools). Without akryum packages. Just install and make step by step
