### ISSUE TITLE
Route canReuse

### ISSUE THREAD

**Issue by nicooprat** [Akryum/meteor-vue-component#59]
Is it possible to tell a component to not be replaced when transitioning between routes? [According to the docs](http://router.vuejs.org/en/pipeline/can-reuse.html):

````js
export default {
    route: {
      canReuse: true
    }
}
````

I have a map that is the same in multiple pages and I'd like to avoid re-render it every time. I'm new to Vue so I may have missed something! I tried this configuration on the map component and on its parents, with no luck. The DOM is the same in all parent components (div > map).

Thanks.

**Comment by Akryum** [comment]
By default, a component is reusable, you don't need to specify it. Maybe your map component is not reused because its parents are different?

**Comment by nicooprat** [comment]
I'm not sure to understand. Yes, parents are different in each route, I guess that reusing components is only useful in this case anyway, isn't it?

**Comment by nicooprat** [comment]
I found a workaround by using a `<component :is="..." keep-alive>` dynamic component, watching the current route and displaying it or not ([idea from the forum](https://forum.vuejs.org/topic/1520/listener-for-changes-to-route/2)). Not ideal, because the map would still be alive even if it's not needed anymore, so that could cause memory problems, but... it works.

````js
// Route

'/explore': {
  name: 'explore',
  component: explore,
  showMap: true
},

// Component

<template>
  <router-view></router-view>
  <component :is="showMap" keep-alive></component>
</template>

<script>
  export default {
    data() {
      return {
        showMap: this.getShowMap()
      }
    },

    methods: {
      getShowMap() {
        return this.$route.showMap ? 'map' : ''
      }
    },
    
    watch: {
      '$route': function() {
        this.showMap = this.getShowMap()
      }
    }
  }
</script>
````

Looks like a lot of code for such a simple thing, I'm sure I missed a better way to do that!

**Comment by Akryum** [comment]
> I'm not sure to understand. Yes, parents are different in each route, I guess that reusing components is only useful in this case anyway, isn't it?
It seems it's only used if a part of the component tree is the same, for example when you have subroutes. Maybe we should post an issue about that in the vue-router repo.

**Comment by nicooprat** [comment]
Right, I should have checked there before mentioning it here. Maybe related to https://github.com/vuejs/vue-router/issues/403. Thanks.
