### ISSUE TITLE
IOS Platform issues

### ISSUE THREAD

**Issue by 7ammer** [Akryum/meteor-vue-component#60]
I've tried setting up [Simple example project](https://github.com/Akryum/meteor-vue-example) for IOS platforms however I'm getting issues when running `meteor run ios`.

The client console complains about TypeErrors: `undefined is not an object (evaluating 'ClientVersions.find') - dev-client.js:56`

Vue's css doesn't seem to be loading either?

<img width="423" alt="screen shot 2016-08-03 at 17 25 32" src="https://cloud.githubusercontent.com/assets/3194029/17373272/67118148-599f-11e6-8fb8-a8dd93278a76.png">

**Comment by Akryum** [comment]
Is it fixed in the latest `akryum:vue-component@0.6.6`?

**Comment by laurentpayot** [comment]
Looks like there are similar errors for Android, as described in #62 …

**Comment by Akryum** [comment]
Do you still have this specific error?
