### ISSUE TITLE
Vue 2.0 compatibility

### ISSUE THREAD

**Issue by Akryum** [Akryum/meteor-vue-component#63]
- [x] akryum:vue
- [x] akryum:vue-component
- [x] akryum:vue-router

**Comment by janat08** [comment]
How is it coming along? Meanwhile Ill get apollo going.

**Comment by Akryum** [comment]
I got Vue 2.0 working, still need to make the hot-reload work.
Next, I'll update the other packages to be compatible.

**Comment by Akryum** [comment]
The latest version of akryum:vue and akryum:vue-component are now compatible with Vue 2.0.
Just install vue@next with npm in your meteor project.

```
meteor update
meteor npm install --save-dev vue@next
```

Note that you shouldn't do that if you use another package like akryum:vue-router or akryum:vue-component as they are not compatible yet.

**Comment by Akryum** [comment]
[Vue-router2](https://github.com/Akryum/meteor-vue-component/tree/master/packages/vue-router2#installation)
