### ISSUE TITLE
Subscription ready

### ISSUE THREAD

**Issue by degger80** [Akryum/meteor-vue-component#75]
Is there any reactive var that shows that subsctiption is ready?

I'm trying to add nested component and path there data fetched from Collection via params:

`<nested-component :esList="esList"></nested-component>`

```
<template>
  <div class="someclass">
    <nested-component :esList="esList"></nested-component>
  </div>
</template>

<script>

import {CollectionItems} from '/lib/collections/CollectionItems'
import NestedComponent from './NestedComponent.vue'


export default {
  name: 'componentName',
  components: {
    NestedComponent
  },
  data() {
    return {
      esList: []
    }
  },
  meteor: {
    subscribe:{
      'collection-items-subscription-name': []
    },
    data: {
     
      esList(){
        return CollectionItems.find().map((item)=>{
          return {
            label: item.name,
            value: item._id
          }
        })
      }

    }
  }
}
</script>
```

The NestedComponent is rendered with empty data (subscription not finished) and not updated when subscription done. In NestedComponent  only 'mounted' event is fired.

**Comment by degger80** [comment]
I've found solution:

```
data(){
  subReady: false
},
meteor:{
  data:{
    subReady(){
      return this.$subscribe('collection-items-subscription-name').ready();
    }
  }
}
```

and render nested component only when subscription is ready:
`<nested-component v-if="subReady" :esList="esList"></nested-component>`

Is this correct use  of  `this.$subscribe(...` syntax ?

**Comment by Akryum** [comment]
I could add something to make this easier.

**Comment by Akryum** [comment]
New in the `1.1.0` release of `akryum:vue` meteor package:

The `$subReady` object on your component contains the state of your subscriptions. For example, to know if the 'thread' subscription is ready, use this *reactive* expression:

```javascript
console.log(this.$subReady.thread);
```

Or in your template:

```html
<div v-if="!$subReady.thread">Loading...</div>
```
