### ISSUE TITLE
HTML is littered with __v attributes which make reading code in dev tools hard

### ISSUE THREAD

**Issue by M4v3R** [Akryum/meteor-vue-component#78]
I don't know if that's exactly an issue of meteor-vue-component, but when I run a simple app with `.vue` components it renders the HTML like this:

![Imgur](http://i.imgur.com/4wTZROw.png)

This makes debugging HTML/CSS in browser dev tools very hard. When looking through official Vue examples I didn't saw these at all, and in a webpack example I did saw them, but they were MUCH shorter (15 chars vs 67 chars). Can something be done to get rid of those attributes? I assume they are for scoped CSS feature, but I don't even use it now, yet they are still there.

**Comment by Akryum** [comment]
It is for scoped CSS, and I'll update it to have shorted attributes.

**Comment by M4v3R** [comment]
@Akryum: Is it possible to add them only to elements that actually use scoped CSS?

**Comment by Akryum** [comment]
Maybe. ^^

**Comment by mwarren2** [comment]
This may be related:
While building meteor, something is adding __v attributes to component code as well and the compiler throws out these messages:

> [ '- invalid expression: :class="{active: (!mouseModel && model  __v3526c1452685d1042a961c804897cdc640f6cca6cdd471b629fbc6de38756ab7>= index) || (mouseModel && mouseModel >= index)}"' ]
[ '- invalid expression: :class="{incomplete: step  __v06909b10feb6b30b0edd6334bda8e34fa4c548289fce08e7d4a98c73f334ef12> stepper.currentStep}"',
  '- invalid expression: v-show="step  __v06909b10feb6b30b0edd6334bda8e34fa4c548289fce08e7d4a98c73f334ef12>= stepper.currentStep"',
  '- invalid expression: v-if="step  __v06909b10feb6b30b0edd6334bda8e34fa4c548289fce08e7d4a98c73f334ef12> 1"' ]
