### ISSUE TITLE
2 dimensional v-for won't work

### ISSUE THREAD

**Issue by janat08** [Akryum/meteor-vue-component#79]
I'm trying to create a table, and it won't let me filter data.array in v-for or access data.array within filter method
http://pastebin.com/nPrR2EzD
i'm also passing the row variable into filter method
basically array is unidentified either way.

Was asked if skills is instance property which I imagine it is not enough of so.

**Comment by Akryum** [comment]
You seem to have difficulties with Vue rather than with the Meteor integration. I suggest that you post this in the [Vue forum](http://forum.vuejs.org/) or [Gitter](https://gitter.im/vuejs/vue).

**Comment by janat08** [comment]
well one dimensional v-for would work
