### ISSUE TITLE
New .vue files need full app restart to be recognized 

### ISSUE THREAD

**Issue by M4v3R** [Akryum/meteor-vue-component#80]
When I have my app started, the HMR module does a great job handling all the changes I make to my single-file components. But when I create a new .vue file while the app is started and try to reference it in other components, I get an ENOENT error - file not found.

**Comment by Akryum** [comment]
Yeah got this too recently, maybe has something to do with Meteor 1.4.2. Which version of Meteor do you use?

**Comment by M4v3R** [comment]
@Akryum Yes, I'm using Meteor 1.4.2 in this app.

**Comment by M4v3R** [comment]
@Akryum Any news on this issue?

**Comment by Akryum** [comment]
This seems to be a Meteor issue, and is being worked on.

**Comment by benjamn** [comment]
Please try this again after running
```
meteor update --release 1.4.2.2-beta.0
```
in an existing app, or
```
meteor create --release 1.4.2.2-beta.0 your-new-app
```
to create a new app using the latest beta version.

**Comment by Akryum** [comment]
@benjamn It's working again! 😄

**Comment by jamiter** [comment]
Hi, so, this issue can be closed right?
