### ISSUE TITLE
Vuex incompatible with vue 2

### ISSUE THREAD

**Issue by janat08** [Akryum/meteor-vue-component#84]
http://pastebin.com/zGfuqwxw
this.callMethod

**Comment by janat08** [comment]
Isn't 1.4.2 error.

**Comment by janat08** [comment]
https://laracasts.com/discuss/channels/vue/vuex-anybody-typeerror-thisstorecommit-is-not-a-function

I'm pretty much following the solution I suppose,

**Comment by janat08** [comment]
Okay after I've dumbed it down to something of a hello world, I imagine once you don't have store for a variable within root you're going to get this error as it is factually would not bind to component, which means you just have to use the meteor method within component. The idea was to have smart object creation which is why I was going for vuex to start off with, so I'd be just declaring the data field within state.

**Comment by janat08** [comment]
On second look it works with createThread. Besides my actions, my getters don't show up within vuex expanded store as well, with root object being empty.

**Comment by janat08** [comment]
Even though I don't map the state or the mutations and they shows up

**Comment by janat08** [comment]
My root instance is at least 7 branches deep with another root within that branch.

**Comment by janat08** [comment]
Well then so I cross referenced what "this" gives at example repo and what I got, and the library doesn't have some exceptional errors.

**Comment by janat08** [comment]
```
 _addAction(action) {
    return (store, ...args) => {
      if (!(store instanceof ExtendedStore)) {
        args.unshift(store);
        store = this.store;
      }

      return action.call(this, {
        store,
        state: this.getState(store.state),
      }, ...args);
    };
  }
}
```
this is what my action amounts to within console, and it has these closures:
Closure (_addAction)
Closure
Closure (meteorInstall.node_modules.meteor.akryum:vuex.client.client.js)
Closure
Global

Please help? I corrected the typo for this.action.mappedAction.

**Comment by janat08** [comment]
Stuck the vuex injection into new vue rather than app layout, and still wouldn't work.

**Comment by Akryum** [comment]
What is your full component code?

**Comment by janat08** [comment]
http://pastebin.com/pFPCKRmp

**Comment by Akryum** [comment]
Which version of Vue are you using?

**Comment by janat08** [comment]
"vue": "^2.0.3",
    "vue-router": "^2.0.0-rc.5",
    "vuex": "^1.0.0-rc.2"

**Comment by janat08** [comment]
lol, i actually checked the vuex version, and its 3.10.8?

**Comment by Akryum** [comment]
Well, you are trying to use an incompatible version of vuex with Vue 2.0 and my Meteor vuex package isn't compatible with Vue 2.0 either.

**Comment by janat08** [comment]
Beautiful, I speculated about such a case within forums, I think; No one acknowledged that.

**Comment by janat08** [comment]
"As for Vuex, even version 0.8 is compatible with Vue 2, so you’re not forced to upgrade. The only reason you may want to upgrade immediately is to take advantage of the new features in Vuex 2, such as modules and reduced boilerplate."

They say it should be fine, whats the problem and is it going to get fixed?

**Comment by janat08** [comment]
Just in case maybe you could assign this to a milestone?

**Comment by janat08** [comment]
At very least porting over some of the convenience functionality would be splendid like reading from state directly rather than having to declare getter for every state.

**Comment by Akryum** [comment]
Well, you can use `mapState` to access the state directly: [documentation](http://vuex.vuejs.org/en/state.html#the-mapstate-helper).

**Comment by aadamsx** [comment]
I think I need vuex for component-to-component communication (Non-Parent to child communication) on a larger scale (lots of state on one page).

Can I install akryum:vuex and start using vuex today?

**Comment by Akryum** [comment]
The Meteor vuex package is only for Vue 1.x, as I will do a different and more generic npm package for vuex 2. You can still install vuex 2 and [follow the guide](http://vuex.vuejs.org/).

**Comment by janat08** [comment]
Oh well, using vuex stand alone without akryum:vuex hasn't occurred to me.

**Comment by janat08** [comment]
to be clear mapstate isn't supported in your package, since you link to vuex 2 documentation.

**Comment by Akryum** [comment]
Yes, vuex2 doesn't work like vuex1.

**Comment by janat08** [comment]
Well then map state shouldn't be available, although I just concluded that
it's essentially the same stuff mapping it through mapstate or getter.

**Comment by janat08** [comment]
Seeing how original vue is hell to debug with it's "common" junk (maybe you could share your secret with them), would you comment on how horrific vuex 2 is? I belief I used their web pack constructor, so it's probably the lib that's shite.
