### ISSUE TITLE
vue-component  not support  lang="css"

### ISSUE THREAD

**Issue by shijunti19** [Akryum/meteor-vue-component#85]
vue-component  not support  lang="css"

[vue-component] Error while compiling in tag <style> using lang css -> in node_modules/mint-ui/packages/switch/src/switch.vue at line 45

<style lang="css">
  @import "../../../src/style/var.css";

  @component-namespace mint {
    @component switch {

**Comment by shijunti19** [comment]
THANK YOU
https://github.com/ElemeFE/mint-ui/
This project needs to support css

**Comment by shijunti19** [comment]
Hello, when are we going to use this update?

**Comment by shijunti19** [comment]
@Akryum The author when are you going to update to the 1.0.0-beta.2 version!
Now only this can use！

**Comment by mwarren2** [comment]
Yes, I find the <style> section of my .vue file is simply being ignored, if that's what we're talking about here.
For the moment I've had to put styles into an external .css file.

**Comment by shijunti19** [comment]
When to repair

**Comment by Akryum** [comment]
@shijunti19 When I'll have the time. If someone want to do a PR to fix this, he is welcomed!

**Comment by Akryum** [comment]
Initial support in `0.8.5`, still need to implement `@import`.

**Comment by Akryum** [comment]
For mint-ui, did you try importing the [built files](https://github.com/ElemeFE/mint-ui/tree/master/lib) instead?
