### ISSUE TITLE
To get best vue, import vue from where? {akryum:vue} or vue?

### ISSUE THREAD

**Issue by maco144** [Akryum/meteor-vue-component#89]
Hello. 
 I am confused as to the preferred way to get Vue imported as your examples have different import statements. Should I be using
import Vue from 'vue';   or
import {Vue} from 'meteor/akryum:vue'; ??

Thank you for your project and answer.

**Comment by Akryum** [comment]
Hi! Thanks! Use `import Vue from 'vue';`
