### ISSUE TITLE
Integrating vuetify project

### ISSUE THREAD

**Issue by ackzell** [Akryum/meteor-vue-component#94]
I have errors in my console after I install the `vuetify` npm package.

```
12:19 $ meteor
[[[[[ ~/Documents/experiments/meteor/lunch-vue ]]]]]

=> Started proxy.
   [HMR] Dev server listening on port 3003
=> Errors prevented startup:

   While processing files with akryum:vue-component (for target
   web.browser):
   packages/vue-component/plugin/tag-handler.js:192:24: tag is not
   defined
   at VueComponentTagHandler.getResults
   (packages/vue-component/plugin/tag-handler.js:192:24)
   at compileTags
   (packages/vue-component/plugin/vue-compiler.js:648:18)
   at compileOneFileWithContents
   (packages/vue-component/plugin/vue-compiler.js:663:12)
   at VueCompo.compileOneFile
   (packages/vue-component/plugin/vue-compiler.js:163:12)
   at packages/vue-component/plugin/vue-compiler.js:84:34
   at
   /Users/amartinez/.meteor/packages/akryum_vue-component/.0.7.11.697
ac7++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modu
les/meteor/vue-component/node_modules/async/lib/async.js:182:20
   at replenish
   (/Users/amartinez/.meteor/packages/akryum_vue-component/.0.7.11.69
7ac7++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_mod
ules/meteor/vue-component/node_modules/async/lib/async.js:317:21)
   at
   /Users/amartinez/.meteor/packages/akryum_vue-component/.0.7.11.697
ac7++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modu
les/meteor/vue-component/node_modules/async/lib/async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (/Users/amartinez/.meteor/packages/akryum_vue-component/.0.7.11.69
7ac7++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_mod
ules/meteor/vue-component/node_modules/async/lib/async.js:221:35)
   at VueCompo.processFilesForTarget
   (packages/vue-component/plugin/vue-compiler.js:68:11)


=> Your application has errors. Waiting for file change.
=> Started MongoDB.
```

I'm thinking there might be something wrong with the code from the vuetify library that prevents meteor-vue-component from reading it properly?

I'm asking a question on that repo as well.

Thanks!

**Comment by aadamsx** [comment]
What does Vuetify provide you over Vue + vue-component + Meteor?

**Comment by ackzell** [comment]
It provides some pre-built Material UI components.

So, it basically builds on top of Vue.js and gives you a set of already made UI layouts and elements you could use in your app. It follows the Google's Material spec for building interfaces.

https://vuetifyjs.com/

**Comment by ackzell** [comment]
I't is more like an add-on rather than a replacement.

**Comment by Akryum** [comment]
Try ignoring the `node_modules` directory like [described in the doc](https://github.com/Akryum/meteor-vue-component/tree/master/packages/vue-component#ignore-files), and import the `vuetify/dist/vuetify.min.css` and `vuetify/dist/vuetify.min.js` files in your app code.

**Comment by ackzell** [comment]
Thank you @Akryum. Worked perfectly.

This way `meteor-vue-component` will not attempt to compile the components from the `vuetify` library and just use whatever already-compiled versions we provide in the `node_modules`folder. Correct?

**Comment by Akryum** [comment]
Correct!
